### ISSUE TITLE
PACKAGE_CONVERGENCE for MAW

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#1034]
Do you have plans to implement the PACKAGE_CONVERGENCE option for MAW as well?
Best regards
Andreas

**Comment by langevin-usgs** [comment]
The MAW Package works differently from LAK, SFR, and UZF, in that it is solved as part of the matrix equations for the Groundwater Flow Model.  We optionally provide additional package convergence information for LAK, SFR, and UZF as there is a separate convergence check for these packages.  For this reason, we're not sure that the additional information is necessary for MAW, but let us know if you think otherwise and feel free to reopen this issue.

**Comment by tandreasr** [comment]
Re: [MODFLOW-USGS/modflow6] PACKAGE_CONVERGENCE for MAW (Issue #1034)



Hi Chris,
of course you're right.
I was just thinking of MODFLOW-2005 where MNW sometimes was a little bit difficult to handle due to convergence problems.
But I forgot that now it is solved within the matrix equations instead of using Picard iterations as before.
Thanks
Andreas
