### ISSUE TITLE
error reading in GWF-GWF exchange file

### ISSUE THREAD

**Issue by kmarkovich-intera** [MODFLOW-USGS/modflow6#1038]
Hello,

I am trying to convert an LGR2 model to MF6 and set up an exchange file using the lgr utils of FloPy. When I try to run the simulation, it crashes with errors:

  336.  TRAN_MF6 Cell is outside active grid domain (1,205,96).
  337. Errors encountered in exchange input file.
 
The cellid that is getting reported to the list file is not anywhere in the simulation.exg file, and also the listing file cellid changes each time I try to run the simulation. It appears that MF6 is replacing some but not all parent cellids when reading in the .exg file, but I can find any rhyme or reason for why it would do that. Any help would be much appreciated. 
[test.zip](https://github.com/MODFLOW-USGS/modflow6/files/9551743/test.zip)

**Comment by langevin-usgs** [comment]
It looks like some of the cells listed in cellidm1 correspond to IDOMAIN values less than 1.  And it also looks like the error message isn't quite right (due to how we handle IDOMAIN = 0 cells), so that's not helping.  I ran this script to confirm the issue:

```
import flopy
sim = flopy.mf6.MFSimulation.load()
exg = sim.get_exchange_file("simulation.exg")
exchange_data = exg.exchangedata.get_data()

gwf1 = sim.get_model("tran_mf6")
idomain_m1 = gwf1.dis.idomain.get_data()

gwf2 = sim.get_model("child4_mf6")
idomain_m2 = gwf2.dis.idomain.get_data()

nidomain0 = 0
for l, r, c in exchange_data["cellidm1"]:
    if idomain_m1[l, r, c] < 1:
        nidomain0 += 1
print(f"There are {nidomain0} exchanges for cellidm1 assigned to cells with idomain < 1")

nidomain0 = 0
for l, r, c in exchange_data["cellidm2"]:
    if idomain_m2[l, r, c] < 1:
        nidomain0 += 1
print(f"There are {nidomain0} exchanges for cellidm2 assigned to cells with idomain < 1")
```

and the result is:

```
There are 336 exchanges for cellidm1 assigned to cells with idomain < 1
There are 0 exchanges for cellidm2 assigned to cells with idomain < 1
```

So it looks like there may be some additional processing that you need to do with the LGR utility in flopy to make sure this doesn't happen.

We will leave this issue open to remind us to fix the error message that you are seeing.

**Comment by kmarkovich-intera** [comment]
Thanks!
