### ISSUE TITLE
UZT Concentrations observations are all zero

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1148]
In the attached model, there are two sets of concentration observations: GWT concentration and UZT concentration. The source of solute in the model is from solute specified in the top layer in the UZF infiltration. The GWT concentrations appear appropriate, but the UZT concentrations are all zero. The GWT concentration observations are in UZF_Example.Chem.ob_gw_out_concentration.csv. The UZT observations are in UZF_Example.Chem.uzt-conc_ob.csv.
[UZT_ObsBug.zip](https://github.com/MODFLOW-USGS/modflow6/files/10736788/UZT_ObsBug.zip)

**Comment by emorway-usgs** [comment]
Hello @rbwinst-usgs, switching from `steady-state` to `transient` in the flow model's `STO` package lead to non-zero concentrations being printed in the UZT observation output file.  For steady-flow conditions, you may want to consider a really long (`perlen` = ~1e6) transient stress period.  You may also consider checking in with at @rniswon on this one - a steady-state simulation with "UZF2" (or "UZF6" - not sure what the official name is) is tricky since a vertical column of UZF objects can be parameterized differently (e.g., VKS).
