### ISSUE TITLE
GNC Package is not working on Windows, but works on Linux (MF6.4.1)

### ISSUE THREAD

**Issue by MostafaGomaa93** [MODFLOW-USGS/modflow6#1315]
I use to run my model on Linux with the GNC package and its okay. When trying to run the same model on Windows. I received the error below which is most likely related to the GNC package. When I deactivate the GNC package, and run the model again on Windows, it runs normally. I am using mf6.4.1

Attached is a small version of the model (only 5 stress periods) for testing. Would appreciate your assistance

![GNC_error](https://github.com/MODFLOW-USGS/modflow6/assets/54531356/685a17f8-9955-4f4a-bdaf-fa8d7a17be25)

[test_GNC.zip](https://github.com/MODFLOW-USGS/modflow6/files/12186150/test_GNC.zip)

**Comment by mjr-deltares** [comment]
Have you resolved this issue in the meantime?

It looks like the program crashes because it tries to set up a ghostnode connection between two nodes that are not actually connected in the discretization: (1,2271) and (1,655). It's really hard to tell why this happens, maybe you can check the GCN data with this lead in mind?

**Comment by langevin-usgs** [comment]
Closing this issue.  Feel free to reopen if it persists.
