### ISSUE TITLE
Parallel simulations in MODFLOW6 

### ISSUE THREAD

**Issue by YozeGholami** [MODFLOW-USGS/modflow6#1363]
Hello there,

I trust this message finds you in good health. Currently, I'm engaged in research involving MODFLOW 6, and I'm utilizing the FloPy library for my work.

I'm exploring the capabilities of parallel simulations to enhance the efficiency of my modeling tasks. While FloPy provides options for setting processors and running simulations in parallel, I've encountered a challenge with MODFLOW's simulation capabilities.

Specifically, I've encountered an error in the process that I'm currently addressing. Your insights or suggestions on this matter would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Amin Gholami

FloPy is using the following executable to run the model: ..\MF6\mf6.exe
FloPy is using C:\Workplace\Python\Training\Modflow6  Example\modflow6-examples-master\14\mpiexec.exe to run C:\Workplace\Python\Training\Modflow6  Example\modflow6-examples-master\MF6\mf6.exe on 2 processors.
mf6.exe - MODFLOW 6.4.1 Release 12/09/2022 (compiled Dec 09 2022 18:18:37)
usage: mf6.exe               run MODFLOW 6 using "mfsim.nam"
   or: mf6.exe [options]     retrieve program information

Options   GNU long option   Meaning 
 -h, -?    --help           Show this message
 -v        --version        Display program version information.
 -dev      --develop        Display program develop option mode.
 -d        --disclaimer     Display program disclaimer.
 -lic      --license        Display program license information.
 -c        --compiler       Display compiler information.
 -co       --compiler-opt   Display compiler options.
 -s        --silent         All STDOUT to mfsim.stdout.
 -l <str>  --level <str>    STDOUT output to screen based on <str>.
                            <str>=summary Limited output to STDOUT.
                            <str>=debug   Enhanced output to STDOUT.
 -m <str>  --mode <str>     MODFLOW 6 simulation mode based on <str>.
                            <str>=validate Check model input for
                                           errors but do not 
                                           assemble or solve matrix 
                                           equations or write 
                                           solution output.
                                                                    
Bug reporting and contributions are welcome from the community. 
Questions can be asked on the issues page[1]. Before creating a new
issue, please take a moment to search and make sure a similar issue
does not already exist. If one does exist, you can comment (most
simply even with just :+1:) to show your support for that issue.
                                                                    
[1] https://github.com/MODFLOW-USGS/modflow6/issues

ERROR REPORT:

  1. mf6.exe: illegal option - -p
mf6.exe - MODFLOW 6.4.1 Release 12/09/2022 (compiled Dec 09 2022 18:18:37)
usage: mf6.exe               run MODFLOW 6 using "mfsim.nam"
   or: mf6.exe [options]     retrieve program information

Options   GNU long option   Meaning 
 -h, -?    --help           Show this message
 -v        --version        Display program version information.
 -dev      --develop        Display program develop option mode.
 -d        --disclaimer     Display program disclaimer.
 -lic      --license        Display program license information.
 -c        --compiler       Display compiler information.
 -co       --compiler-opt   Display compiler options.
 -s        --silent         All STDOUT to mfsim.stdout.
 -l <str>  --level <str>    STDOUT output to screen based on <str>.
                            <str>=summary Limited output to STDOUT.
                            <str>=debug   Enhanced output to STDOUT.
 -m <str>  --mode <str>     MODFLOW 6 simulation mode based on <str>.
                            <str>=validate Check model input for
                                           errors but do not 
                                           assemble or solve matrix 
                                           equations or write 
                                           solution output.
                                                                    
Bug reporting and contributions are welcome from the community. 
Questions can be asked on the issues page[1]. Before creating a new
issue, please take a moment to search and make sure a similar issue
does not already exist. If one does exist, you can comment (most
simply even with just :+1:) to show your support for that issue.
                                                                    
[1] https://github.com/MODFLOW-USGS/modflow6/issues

ERROR REPORT:

  1. mf6.exe: illegal option - -p

(False, [])

**Comment by mjr-deltares** [comment]
Hello Amin,

This does not appear to be an issue with the program. From your log I see that the executable is the December release. Our pre-compiled release binaries do not have parallel capabilities. If you want to try parallel MODFLOW 6, you would have to compile the code yourself. You could consider having a look at the PARALLEL.md in this repo for some guidance. Note however that we are still developing and refining a lot of this functionality. The available documentation and support are most likely not sufficient for general use.

**Comment by jdhughes-usgs** [comment]
Parallel capabilities first became available in v 6.4.2 and are considered beta at this stage. Users need to compile MODFLOW 6 in order to get parallel capabilities. Information on compiling the parallel version of MODFLOW 6 can be found at:
 
[https://github.com/MODFLOW-USGS/modflow6/blob/develop/PARALLEL.md](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMODFLOW-USGS%2Fmodflow6%2Fblob%2Fdevelop%2FPARALLEL.md&data=05%7C01%7Cjdhughes%40usgs.gov%7Cee3f59b5d6934e1021d708dbbb72ea4b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638309874444783220%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F4TG0YwyaN61DuwHC45dbHv95APheUGTgag0cerT6W4%3D&reserved=0)
 
Compiling the parallel version is still a challenge on Windows. But we hope to work the Windows issues out in the next few releases. Using the Windows Subsystem for Linux (WSL) is the way that we have gotten around Windows issues at this point. Instructions for compiling on WSL can be found at
 
[https://github.com/jdhughes-usgs/parallel-modflow6-class/blob/main/wsl_setup.md](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjdhughes-usgs%2Fparallel-modflow6-class%2Fblob%2Fmain%2Fwsl_setup.md&data=05%7C01%7Cjdhughes%40usgs.gov%7Cee3f59b5d6934e1021d708dbbb72ea4b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638309874444783220%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GLABinsIQAvOAXiOtRkhwDw%2BuNAAJ%2F1UDPrjuHw84CU%3D&reserved=0)
 
Also, parallelization relies on the multi-model concept in MODFLOW 6. As a result, to run on 2 processors you need a simulation with at least 2 models coupled by exchanges. FloPy includes a model splitter that can be used to split a single model into multiple models. A demonstration of the FloPy model splitter can be found at
 
[https://flopy.readthedocs.io/en/latest/Notebooks/mf6_parallel_model_splitting_example.html](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fflopy.readthedocs.io%2Fen%2Flatest%2FNotebooks%2Fmf6_parallel_model_splitting_example.html&data=05%7C01%7Cjdhughes%40usgs.gov%7Cee3f59b5d6934e1021d708dbbb72ea4b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638309874444783220%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=26to9fxw%2B2Z8xeoO30qluc%2B3nx2EQrQadE3oEnlCqGE%3D&reserved=0)
 
And finally, since parallel MODFLOW 6 capabilities are beta at this point we are only providing limited support to users trying to use the parallel version.
