### ISSUE TITLE
downstream reach diverting water from another segment

### ISSUE THREAD

**Issue by ougx** [MODFLOW-USGS/modflow6#1433]
we have a stream network that includes complicated canal system like the one below

![image](https://github.com/MODFLOW-USGS/modflow6/assets/5205922/9b897cc0-8c49-4bf0-9e69-ebcdbaa48769)

Reach 1 and 3 is a canal. Reach 3, downstream of Reach 1, also diverts water from Reach 2. Because the `ustrf` values for Reach 3 and 4 are one as they are downstream of Reach 1 and 2, respectively, the sum of all downstream to Reach 2 will be 2. How can we handle this in MF6 SFR, hopefully without adding new reaches? Can we get rid of `ustrf`? As its function seems to be duplicated when using fraction diversion.

Thanks!

**Comment by emorway-usgs** [comment]
Hello @ougx , I wonder if you could alter the SFR construct just slightly to something like what's shown below to help alleviate the concern with the `ustrf` parameter?  

In the diagram below, the curved arc over segment 4 is meant to indicate that there is no physical or numerical connection between reaches 1 & 4.  Segment 2 is connected to both 4 and 5, with 5 specified as a diversion in the `DIVERSIONS` block of the SFR input file.  Flow will only be diverted into 5 based on input appearing in the `PERIODS` block(s), otherwise outflow from 2 dumps to 4.  

For the diagram at the bottom, the input in the `PACKAGEDATA` block might appear something like what's shown below (fictitious values, but I'm thinking the values appearing in the `ustrf` and `ndv` columns would go along with the diagram, which I think is what you're attempting to sort out):

```
<rno> <cellid> <rlen> <rwid> <rgrd> <rtp> <rbth> <rhk> <man> <ncon> <ustrf> <ndv>
    1 (1, 1, 1)    12      5  0.001  10.0    1.0   0.1 0.035      1     1.0     0
    2 (1, 2, 1)     8      5  0.001  10.0    1.0   0.1 0.035      2     1.0     1
    3 (1, 1, 2)     8      5  0.001   9.5    1.0   0.1 0.035      2     1.0     0
    4 (1, 1, 1)    12      5  0.001   9.5    1.0   0.1 0.035      1     1.0     0
    5 (1, 2, 2)     2      5  0.001  9.75    1.0   0.1 0.035      2     0.0     0
```

![new_construct](https://github.com/MODFLOW-USGS/modflow6/assets/3236576/a972cc24-1918-4a23-8e6c-7e67de63e572)

**Comment by ougx** [comment]
Hi @emorway-usgs, thanks for providing the solution.

You provided a solution without using MOVER package and it keeps the routing in sync within one iteration. But we have already set up the reach numbers so we are now trying to avoid altering stream network structure and we may end up using MVR.

Nevertheless, could we get rid of `ustrf` in the SFR input? The only usage I could think of it is diverging branches like a river delta. But this could be implemented as `diversions`.
