### ISSUE TITLE
Writing package name in flow outputs in the LIST file

### ISSUE THREAD

**Issue by ougx** [MODFLOW-USGS/modflow6#1510]
When the PRINT_FLOW option is activated, can we also include the package name in the output? This will be helpful to extract the flow results using `grep`.

For example, for a DRN output:
```
 DRN PACKAGE (HATCHERY) FLOW RATES   PERIOD    191   STEP        1
 -----------------------------------------------
   NUMBER   CELLID                    RATE      
 -----------------------------------------------
     1      (1,277,124)           0.0000000     
 -----------------------------------------------
```
can be changed to: 
```
 DRN PACKAGE (HATCHERY) FLOW RATES   PERIOD    191   STEP        1
 ---------------------------------------------------------
   PACKAGE  NUMBER   CELLID                    RATE      
 ---------------------------------------------------------
  HATCHERY      1      (1,277,124)           0.0000000     
 ---------------------------------------------------------
```
so I can `grep "^  HATCHERY" output.lst > drn.lst`. Or should it be another option that we could write flows to a CSV.

**Comment by langevin-usgs** [comment]
Hey @ougx, I understand that scraping the list file could be used here to get these flows, but, like you mentioned, wouldn't a csv from a drn observation be better suited for this?

**Comment by ougx** [comment]
Hi @langevin-usgs, yes, we did try this option and it worked. But it can be inconvenient to set up the OBS file when there are a large number of boundary cells; and especially when we need to change the the number of boundary cells frequently during model development.

**Comment by langevin-usgs** [comment]
I understand that it might be inconvenient to set this up with OBS, but with flopy or a GUI it should be pretty straightforward.  And with OBS, there is the benefit that values are written for every time step.  With your list file approach, the list file can get very large, and if you don't print the budget for every time step, you won't get the flows for every time step.  I think we could consider adding the package name to that table, but that table is really designed for visual inspection rather than more comprehensive post processing.

**Comment by ougx** [comment]
Thanks @langevin-usgs. I think the package name can also help navigate the list file for visual inspection whenever the table is larger than one page(screen).

**Comment by langevin-usgs** [comment]
Closing as this can be done other ways.
