### ISSUE TITLE
UZF sometimes does not report UZET > 0 for cases where it seems like UZET should be greater than 0

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1542]
**Describe the bug**
In a model where the UZF ET is simulated and the head is below the cell top sometimes UZET is reported as 0 in the UZF budget csv file.

**To reproduce**
The attached file contains two models. The models are identical except that in importedOneTenth, the model top is 0.1 and in Imported1, the model top is 1. The heads in both models are always less than the top of the model by at least 0.1 m. However, the unsaturated zone ET is 0 in importedOneTenth but is greater than 0 in Imported1.

**Expected behavior**
Both models should have unsaturated zone ET values greater than 0.

[imported.zip](https://github.com/MODFLOW-USGS/modflow6/files/13866265/imported.zip)

**Comment by emorway-usgs** [comment]
Hello @rbwinst-usgs, I took a look at this model and the UZF parameterization seemed a bit odd.   The saturated water content was set to 0.95 with an initial water content of 0.90.  As soon as the model is turned loose, this leads to a huge slug of UZ drainage to the saturated zone where the specific yield was specified as 0.2.  This then leads to a rather large spike in gw heads well above land surface, and since the unsaturated zone becomes inundated, i.e., there is no unsat zn, there is no `UZET`.  Resetting the UZF parameters to something more reasonable (see attached) seems to have led to the expected behavoir.  Let me know if you still see something amiss.
[Imported1.uzf.txt](https://github.com/user-attachments/files/16602130/Imported1.uzf.txt)
