### ISSUE TITLE
rcha with noflows

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#1804]
**Describe the bug**
It seems rcha (rch using READASARRAYS) can be used with a constant value (didn't try variable arrays) when there are noflow cells in layer 1. This is great, but I would have expected this to not work. Can the documentation be updated to reflect this functionality?

**Comment by langevin-usgs** [comment]
This behavior is intentional.  With READASARRAYS, values are provided for every cell in the layer of a grid, even for those cells with IDOMAIN values less than one.  Note that EVTA works the same way.  For list-based packages, we do not allow stresses to be assigned to a cell with an IDOMAIN value less than one.  

Will add the following to the READASARRAYS keyword description in the mf6io guide.

_When READASARRAYS is specified, values must be provided for every cell within a model layer, even those cells that have an IDOMAIN value less than one.  Values assigned to cells with IDOMAIN values less than one are not used and have no effect on simulation results._
