### ISSUE TITLE
Throw error if BOUNDNAME listed in obs package does not exist

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#1939]
I just accidently set up a DRN obs package where the boundnames were wrong (not listed in the period data). Rather than print in error, MF6 prints 0.30000000E+31 for all the values. I feel like this should result in an error that stops model execution. 

Though now that Im writing this, is the current functionality to address situations were boundnames might exist in later kpers? I suppose looking ahead in the period data just to check boundnames would not fit well into the mf6 framework and would be inefficient.

version 6.5.0

**Comment by jdhughes-usgs** [comment]
Because observations apply to the entire simulation period, a no data value (3e30) is written if a specific boundary condition (location or boundname) does not exist in a stress period. We do not look ahead in any of the files so it is not possible to error check for whether there is every anything to observe for any observations.

I do not think we want to terminate with an error but it might possible to issue a warning if nothing is observed at an observation.
