### ISSUE TITLE
CSUB observation values may not be calculated 

### ISSUE THREAD

**Issue by RichardWinston** [MODFLOW-USGS/modflow6#300]
With the following observation types, the values that are saved never change.
coarse-theta, delay-theta, delay-thickness, theta, thickness-cell
[Delay_Bug.zip](https://github.com/MODFLOW-USGS/modflow6/files/4167921/Delay_Bug.zip)

**Comment by jdhughes-usgs** [comment]
See @jdhughes-usgs comment in #302. 

All observations that are not `*-cell` or `coarse-*` `CSUB` observations must specify interbed numbers `icsubno` or `boundname` instead of `cellid`.

Current version of the code does not have the issue reported in #300 if `CSUB` observations are correctly specified (see **figure included below** which shows all observations in example provided with corrected `CSUB` observations).

However, the `CSUB` source has been modified to report `NODATA` values for observations that are not calculated during steady-state stress periods. Observations that are not calculated for steady-state stress periods include:

1. `SK`
2. `SKE`
3. `SKE-CELL`
4. `SK-CELL`
5. `DELAY-PRECONSTRESS`
6. `DELAY-GSTRESS`
7. `DELAY-ESTRESS`
8. `PRECONSTRESS-CELL`
9. `DELAY-PRECONSTRESS`

`mfio.pdf` has been updated to reflect this change.

![image](https://user-images.githubusercontent.com/2073498/77429054-72be4d00-6daf-11ea-8a9b-e5265072c1f2.png)
*Note:* TEST observations are not shown since no data (`NODATA`) are available for these observations since they are specified for a `boundname` that does not exist.
