### ISSUE TITLE
CSV_OUTPUT for advanced stress packages

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#357]
Hi Chris,
do you see any chance to provide an output of the convergence history for SFR, LAK & MAW packages similiar to the one provided by the CSV_OUTPUT option of the IMS package?

In my opinion this is quite important in order to obtain information, why a certain advanced package doesn't coverge.

Currently only the last value of head and residual change are written to list file and this only, if they exceed the limits, e.g. in routine sfr_cc().

Thanks and best regards
Andreas

**Comment by langevin-usgs** [comment]
Hi @tandreasr, I can see why this might be beneficial.  Most of the convergence problems that we are seeing are due to one of the advanced stress packages (MAW, LAK, SFR, UZF).  As you know, the _cc() routines are called within the picard iteration loop of the IMS solver, so that would be one logical place to write convergence history if requested by the user.

Our problem at the moment is that we have a number of ongoing MODFLOW 6 efforts that are taking most of our time.  Once we are further along with those, we can start to work on some of these feature requests.  Alternatively, you are welcome to submit a pull request if you feel that this is something you can implement yourself.  You can contact me directly if you'd like to discuss this further.

**Comment by jdhughes-usgs** [comment]
closed by https://github.com/MODFLOW-USGS/modflow6/commit/19cfad2f9d156912b1336f07e89e4cf804cd9a93 and https://github.com/MODFLOW-USGS/modflow6/commit/a3246bbe5aa050f4532f0456c7500a50cf234c3a
