### ISSUE TITLE
Splitting Rejected Infiltration and GW Exfiltration when moving to MVR package !

### ISSUE THREAD

**Issue by MostafaGomaa93** [MODFLOW-USGS/modflow6#455]
Is there any way to split the Rej-inf and GW Exfiltration to the mover package? I want to move only the rejected infiltration to the reaches of SFR package but not the GW exfiltration.

the second issue: why I received this error when choosing the option FACTOR in the mvr package?

 Solving:  Stress period:     1    Time step:     1
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source            
mf6.exe            00007FF7F1EC0DD9  __libm_pow_e7               0  Unknown
mf6.exe            00007FF7F1D2C4F7  SFRMODULE_mp_SFR_        3960  gwf3sfr8.f90
mf6.exe            00007FF7F1D2A496  SFRMODULE_mp_SFR_        3294  gwf3sfr8.f90
mf6.exe            00007FF7F1D1B7C8  SFRMODULE_mp_SFR_        1379  gwf3sfr8.f90
mf6.exe            00007FF7F1C4A9AC  GWFMODULE_mp_GWF_         627  gwf3.f90
mf6.exe            00007FF7F1DAD10D  NUMERICALSOLUTION        1265  NumericalSolution.f90
mf6.exe            00007FF7F1DD1DD4  SOLUTIONGROUPMODU          90  SolutionGroup.f90
mf6.exe            00007FF7F1D9ABC9  MAIN__                    141  mf6.f90
mf6.exe            00007FF7F1ED3762  Unknown               Unknown  Unknown
mf6.exe            00007FF7F1ED3B54  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF87ECC7BD4  Unknown               Unknown  Unknown
ntdll.dll          00007FF880C6CE51  Unknown               Unknown  Unknown

**Comment by emorway-usgs** [comment]
@MostafaGomaa93 Regarding your first question:

> Is there any way to split the Rej-inf and GW Exfiltration to the mover package? I want to move only the rejected infiltration to the reaches of SFR package but not the GW exfiltration.

I think the response to this issue will provide a satisfactory solution for you: 
https://github.com/MODFLOW-USGS/modflow6/issues/383

**Comment by MostafaGomaa93** [comment]
seems with the current MF6 version, it's not possible to split them and maybe this will be considered in the future as you suggest

**Comment by emorway-usgs** [comment]
@MostafaGomaa93 Hmm, my comment on #383 wasn't as clear as I had hoped.  You can split them.  You can handled rejected infiltration in UZF using a MVR connection (e.g., UZF to SFR) and deactivate `GWSEEP` so that UZF won't simulate gw exfiltration.  Next, instantiate the DRN package and put drains at land surface and use AUXDEPTHNAME like you would use SURFDEP in UZF.  This will simulate exfiltration, and as long as you don't connect the DRN exfiltration to anything, it won't be routed.

**Comment by langevin-usgs** [comment]
Those features are on the develop version.  Unless you can compile the code, you'll need to wait until next month when they are released.

**Comment by MostafaGomaa93** [comment]
Okay, what about the second error I mentioned when using the FACTOR option
Is that error due to my parameters or its something will be solved with the new version?

**Comment by langevin-usgs** [comment]
No way to tell what that error is without more details.  We have lots of tests with the FACTOR option and we haven't had any problems.

**Comment by MostafaGomaa93** [comment]
@emorway-usgs : For the solution that you suggest, there is no AUXDEPTHNAME in the DRN package. you mean to assign a value in the AUXMULTNAME or where exactly I can assign the value that will act like the SURFDEP in the DRN?

**Comment by MostafaGomaa93** [comment]
@langevin-usgs:
actually the error appears with all option except the EXCESS one

**Comment by emorway-usgs** [comment]
@MostafaGomaa93 My apologies, I didn't realize AUXDEPTHNAME was on the develop branch and has yet to be released.  However, you could probably still put a drain at some depth below but near land surface to keep the water in the two pathways you described separate in the list file water budgets.

**Comment by MostafaGomaa93** [comment]
@emorway-usgs : okay no prob. thanks anyway for trying to help

**Comment by langevin-usgs** [comment]
There is a problem (ex27-advpakmvr) that comes with the distribution that uses FACTOR.  It works fine on my machine.  I suspect there is something else wrong.

**Comment by MostafaGomaa93** [comment]
I notice that reducing the number of uzf cells that will be used in the mvr package as providers let the error appears at stress period 50 instead of 1. and reducing more and more the number of provider cells lets the error disappear but this doesn't fit what my simulation.

**Comment by MostafaGomaa93** [comment]
please could you test this sample on your machine
with option FACTOR = 1, the model gets stuck at stress period 1
with option EXCESS = 0 which should behave as FACTOR = 1, it gets stuck at stress period = 56 

https://www.mediafire.com/file/hanyxu9j02ekj2c/transient_model.zip/file

My major problem is that I am an MSc student in ITC, University of Twente who needs to submit my thesis in July and I am trying to let the model work. I limit the number of stress periods from 2550 to 760 to let the model work due to the uzf memory problem. But now I need to solve the MVR problem to have something to show for my thesis, so I would appreciate a lot if you could test my model.

**Comment by emorway-usgs** [comment]
@MostafaGomaa93 Please give the exe found below a try.  Hopefully this will fix your memory issues.  I've included an updated version of the input instructions for you as well.  With these instructions, you could try implementing the UZF-DRN split described earlier in this thread for partitioning the rejected infiltration and groundwater discharge to land surface.  

ftp://ftpext.usgs.gov/pub/wr/nv/carson.city/Morway/mf6_develop/

[Note, you'll have to paste the path above into your windows explorer (not internet explorer) or equivalent.  If git makes a hotlink out of it, that won't work]

**Comment by MostafaGomaa93** [comment]
@emorway-usgs  very much appreciated !!!. Thank you, the model works to the end and the UZF and MVR problems are gone.

**Comment by MostafaGomaa93** [comment]
@emorway-usgs  
For what you proposed about using the DRN package to simulate gw exfiltration.

According to what I know, the MF6 has no option for re-infiltration. but with the use of DRN to simulate gw exfiltration, this gw exfiltration can be moved using the MVR to the UZF and will be considered as re-infiltration.
what do you think from the hydrological point of view?

**Comment by emorway-usgs** [comment]
@MostafaGomaa93 The suggestion I offered was to help keep track of rejected infiltration versus groundwater discharge in your budget output.  These different sources become really important to keep separate when it comes to the transport problem, particularly in agricultural areas where the associated concentrations can be quite different.  

I don't understand why you would return drainwater to land surface, especially if you're thinking of doing this in the same cell?  If your drain is near land surface, then presumably the cell is too saturated to accept the water it just discharged?  If you put the drain at depth and you want to 'move' the drained water to the land surface, then the real-world system you're modeling would need some sort of pump to lift the water.  From a transport perspective, particularly in ag areas, drain water is usually of poor quality (in my experience, anyway) and not something folks would want applied to land surface.

If you are instead thinking of using a drain near land surface in a particular cell(s), and are thinking of using MVR to 'cascade' groundwater discharge (exfiltration) captured with the DRN package to a down slope neighboring cell's UZF object for simulating overland runoff and reinfiltration, then this may work.  That's a very interesting idea. If this is what you're thinking trying out, please let us know how it turns out.

**Comment by MostafaGomaa93** [comment]
yes exactly, my idea is the last part you mention  

using MVR to 'cascade' groundwater discharge (exfiltration) captured with the DRN package to a down slope neighboring cell's UZF object for simulating overland runoff and reinfiltration

**Comment by emorway-usgs** [comment]
@MostafaGomaa93 Because UZF is listed as both a provider and a receiver, I would think your idea of cascading rejected infiltration in the same way you are thinking of cascading groundwater discharge should work. So instead of DRN-to-UZF, you want to connect UZF-to-UZF?  Sounds like a neat idea, and I am curious to hear how this works for you.  It'll be up to you to work out the relative percentages if you want to partition the cascading runoff water among multiple down-slope cells, this is not calculated automatically.  Thus, I think you'll want to select the 'fraction' option for the `mvrtype` and then specify what the fraction using the `value` term shown below (from mf6io.pdf):
![mvr_001](https://user-images.githubusercontent.com/3236576/85043967-de5f4e80-b141-11ea-9852-d69be09e4321.png)

**Comment by MostafaGomaa93** [comment]
@emorway-usgs 
I apply the cascading of the rejected infiltration between the Upslope UZF cells among their neighbouring downslope UZF cells and SFR reaches and I noticed in the water balance of the UZF package, the values of (FROM_MVR) and (Rej-INF-To-MVR) are relatively so high compared to other fluxes and I still don't know why. Is there any kind of repetitions regarding the calculations of these two fluxes!. Although I make sure that the sum of the relative percentages between the Upslope cell and its neighbouring downslope cells are =< 1.

**Comment by emorway-usgs** [comment]
It may be that when you cascade water in the way you have described that the downstream receiving UZF object(s) also reject the "moved" water, thus moving it again.  In this way, the same moved water could potentially be double- or triple-counted (or more), leading to the large magnitude of (FROM_MVR) you are observing in budget list?  That's my best guess, anyway.  

Please keep in mind your specific application sounds like your dabbling in rainfall-runoff modeling, a process that MF6 isn't specifically designed for.  That is to say, I like your thinking on how you wanted to use MVR, but it may be stretching the utility a bit further than it was designed for.

**Comment by MostafaGomaa93** [comment]
I will give a try to understand and remove this kind of repetition. I am willing to write a paper from my MSc work and I guess if I manage to solve this problem, this re-infiltration concept will be a good application of new capabilities of MODFLOW 6 (In my opinion).

**Comment by MostafaGomaa93** [comment]
@emorway-usgs  I was thinking in that way and want to ask about your opinion

from the budget file: with symbols like FROM_MVR = Re-inf   and    Rej_INF-To-MVR = Rej
for each stress period:
if: difference bewteen Re-inf - Rej = +ve, then Re-inf_corrected = difference   and     Rej = 0
if: difference bewteen Re-inf - Rej = -ve, then Re-inf = 0    and    Rej_corrected = difference

I see the fluxes after this modification is within the same order of magnitude of other fluxes of the water budget, but I am not 100% sure if hydrologically this modification is valid.

This re-infiltration concept enhance the groundwater recharge and the streamflow discharge
