### ISSUE TITLE
Plans for solute and heat transport 

### ISSUE THREAD

**Issue by pya** [MODFLOW-USGS/modflow6#459]
I am interest in heat transport in MF6. Therefore, I had a look the [transport branch](https://github.com/MODFLOW-USGS/modflow6/tree/transport). In the file `/src/Model/GroundWaterTransport/gwt1.f90` I found under the ToDo section the item
[ `heat transport input`](https://github.com/MODFLOW-USGS/modflow6/blob/transport/src/Model/GroundWaterTransport/gwt1.f90#L22) and [`add separate heat transport model?`](https://github.com/MODFLOW-USGS/modflow6/blob/transport/src/Model/GroundWaterTransport/gwt1.f90#L35) .

I do have a few questions:

1. What is the time plan to have an official release of MF6 with transport enabled?
1. Will there be specific heat transport input files?
1. Will there be a separate heat transport model?
1. If yes, will the model account for heat exchange with the porous medium?

**Comment by langevin-usgs** [comment]
Hi Mike, here a few answers:
1.  Not sure exactly when it will be officially released.  It is highly functional at the moment and we are continuing to refine and document.  You can follow the development on this transport branch (and in the autotest folder) and see how it's coming along.  
2.  Our plan is to have separate input files for heat transport, but not in the first release.  At the moment you would have to use the heat/solute analogy to do heat transport.  There are papers and reports that describe this approach.
3.  Yes, there probably will be a separate heat transport model, but it will likely be a shallow shell over the top of the existing solute transport model.
4.  In the heat/solute analogy approach, you can currently approximate heat exchange with the porous medium through a sorption term.  The plan for the heat transport model/input files will be to allow the user to enter native thermal units instead of solute equivalents.

**Comment by pya** [comment]
Hi Chris,

Thanks for you answers. My answers to your answers with matching numbering:

1. I am fine with using the non-released code straight from the repo / branch, provided the user interface, i.e. the file formats don't change (too much). I would also go without a (complete) documentation. Some more or less comprehensive and stable example input files would be really helpful though.  ;)
I've been following the repo since mid June 2019 and already have 1000+ mails to `MODFLOW-USGS/modflow6 <modflow6@noreply.github.com>` in my email client folder for MF6.
2. I am aware of the heat/solute analogy and willing to apply it myself, if necessary. Having things pre-made is just easier and less error-prone.
3. Good. Again, I am ready to use it from an active  development branch, provided it is mainly stable to avoid changing my code too many times.
4. Yes. I am aware of this. Again, I would prefer "buy" over "make" here. ;) 

I still have a few months until our project will get into the heat transport phase. I hope MF6 transport will be close to release-ready by then.
