### ISSUE TITLE
Proposal: Output Control for individual layers

### ISSUE THREAD

**Issue by jch-deltares** [MODFLOW-USGS/modflow6#525]
This is meant as a proposal to limit the size of the output files. In the OC is it not possible to specify the output of individual layers. For large models this result in large output files while for a lot of model calculations (for example scenario's) only the output of specific layers is necessary. Is it possible to develop an option to specify the output options for the individual layers? 

Thanks and best regards, 

Joachim Hunink

**Comment by langevin-usgs** [comment]
We recognize that for very large models, it might be nice to control the output by layer; however, we've found that this complicates everything downstream (output post processing with flopy, MODPATH, and MT3D-USGS, for example), because we can't count on a full grid's worth of information.  It is unlikely that we will add the capability to write only certain layers to output files.
