### ISSUE TITLE
LAK obs output file not reporting gw exchange

### ISSUE THREAD

**Issue by emorway-usgs** [MODFLOW-USGS/modflow6#534]
I recently noticed that the reported inflows and outflows for the LAK package's observation output were not balancing.  Fortunately everything balances according to the list file.  It looks like lak.obs output is missing the calculated gwexchg terms.  For example, the output in the listing file suggests that for my particular simulation, the gwexchng term is quite large:

![Lak_bal_1](https://user-images.githubusercontent.com/3236576/89104732-591db980-d3d0-11ea-9ca5-a1e8ebca8dac.png)
![Lak_bal_2](https://user-images.githubusercontent.com/3236576/89104733-5cb14080-d3d0-11ea-9de5-e7e50f316add.png)

But as you can see here the modelfile.lakobs is writing 0's instead:
![lakobs](https://user-images.githubusercontent.com/3236576/89104753-7b173c00-d3d0-11ea-894b-089c9a409b3c.png)

Coincidentally, I'm also noticing that the `TO_MVR` in the listing file doesn't match what's written under the `LAKMVR_OUT` column heading in the LAK observation output file.

I should note that I just pulled all the latest on the develop branch, so this reflects the most recent code changes on that branch

**Comment by emorway-usgs** [comment]
Here is the model I used that should recreate the issue.  One additional note is that I'm on the transport branch, so perhaps there are some updates in `develop` that need to be ported into `transport`?
[lakBudget_issue.zip](https://github.com/MODFLOW-USGS/modflow6/files/5017090/lakBudget_issue.zip)

**Comment by langevin-usgs** [comment]
The transport branch is no longer under development.  Transport was merged into develop.  We are going to delete the transport branch.

**Comment by emorway-usgs** [comment]
I can confirm that the issue is still present with all the latest developments on the `develop` branch

**Comment by langevin-usgs** [comment]
So it turns out that this is actually an input error.  If you want a sum of all groundwater leakage to a single lake, then you need to specify the boundname for the lake, not the lake number, in the obs input file.  In your case, the lake is called "reservoir1", so if we use that in the lake obs input file as

![image](https://user-images.githubusercontent.com/3372403/89425875-1bd26800-d6ff-11ea-8c90-58bc879518ce.png)

Then the observation value matches the value shown in the list file.

![image](https://user-images.githubusercontent.com/3372403/89425753-ffcec680-d6fe-11ea-91b0-e81d90e9d690.png)

In your case, the first value "1" was being read as the lake number and then the code was expecting to find the connection number (iconn) next, but since you didn't specify one, it assumed it was zero.  So we should trap for this an issue an error, and perhaps better describe this in the mf6io.pdf guide, so we'll leave this issue open.  The ID1 and ID2 obs input was implemented so that we could have very fine grained control of what we could "observe" but without better error checking it can be confusing.

**Comment by emorway-usgs** [comment]
Fixed with #710
