### ISSUE TITLE
Possible issue with FLOW_IMBALANCE_CORRECTION keyword in FMI

### ISSUE THREAD

**Issue by emorway-usgs** [MODFLOW-USGS/modflow6#609]
The attached model crashes when the FLOW_IMBALANCE_CORRECTION keyword is included in the OPTIONS block of the FMI package.  Without this keyword, the model successfully runs.  

[ex-gwt-modsim_flow_imbalance_correction.zip](https://github.com/MODFLOW-USGS/modflow6/files/5727086/ex-gwt-modsim_flow_imbalance_correction.zip)

**Comment by langevin-usgs** [comment]
Turns out this is actually a bug in the mf6 program, because nbound isn't set in the UZF Package.  When GWT tries to calculate the flow residual for a cell, in order to compensate for that residual with the FLOW_IMBALANCE_CORRECTION option, it sees nbound as zero.  Simple fix is to set uzf.nbound to uzf.maxbound right after uzf.maxbound is set.  Will submit fix.  Thanks for submitting this, @emorway-usgs.  Good eye.
