### ISSUE TITLE
Transient transport on steady state flow field

### ISSUE THREAD

**Issue by briochh** [MODFLOW-USGS/modflow6#760]
Hi All, There is every chance that I am missing something here but I am following a pretty circular path trying to efficiently simulate transient transport, with time varying input concentrations (for e.g. in recharge), on a steady state flow field. This used to be pretty straight-forward in the MODFLOW-MT3d world but seems a little less intuitive(/possible?) in MF6. 

I get that the steady state flow model (gwf) and transient transport model (gwt) will be time discretized differently and therefore can't sit in the same mf6 simulation. I can overcome this through the FMI package. However, following the example https://modflow6-examples.readthedocs.io/en/latest/_notebooks/ex-gwt-mt3dsupp631.html it seems that to simulate time varying concentration on boundary conditions in the gwt, the number of gwf stress periods needs to be the same as number of gwt stress periods. Is this right? 

If this is the case then in order to run a transport simulation with, for example, 100 stress periods of varying recharge concentration we need to run 100 consecutive steady state flow stress periods? While for small models this may not be too much trouble, for a larger model there is a significant overhead prepping, solving and saving each stress period (even though the flow solution should not change and convergence occurs within 1 or 2 iteration), and then also a big hit on the disk! 

This makes me feel like I have missed something. Is there a way of using the single steady state stress period outputs from the flow model but passing through the transient concentration input to the transport model? Obviously for recharge concentration one can use flow model recharge and desired concentration input function to build an transient SRC package load array but this is less straight forward for head-dependent boundaries. For these, I can always pull the flow terms from flow model output (CBC) and construct a transport model SRC package on the fly but this does feel a little cumbersome. 

Is there a more elegant solution for specifying transient boundary condition concentration for a transport model within a steady state flow field? 

Hope someone can help!

**Comment by langevin-usgs** [comment]
Hi @briochh, I wish we could tell you that we had a silver bullet for this, but at the moment we don't (except maybe the API, but I wouldn't recommend that for this purpose).  We knew that transient source concentrations would be limiting for the situation you describe, but we wanted to gain some experience with GWT before supporting file-based source/sink concentration input.  It's not hard to support input for this, but there are a couple of different ways we could do it, and we need to think it through in light of some of our other ongoing developments.  Although the MT3D SSM input file does support what you want to do, it is cumbersome and difficult to manipulate.  We are working on a mf6 official release now, and once that is out, we'll make this a priority.

**Comment by briochh** [comment]
Thanks @langevin-usgs, give me a shout if you want any usage input from my end. Conceptually at least it seems like it would make most sense to explicitly specify concentration inputs at the SSM package end but I understand that there are a few use cases to consider here!
Happy to test any devs on this.

**Comment by langevin-usgs** [comment]
Hey @briochh, I have this working now and am close to merging in the pull request (#766) with the implementation.  The basic idea is as follows.  We've added another block to the SSM package called FILEINPUT.  So now the SSM input looks like this

![image](https://user-images.githubusercontent.com/3372403/129392402-df19b33d-ddda-4489-bcaf-cb5353a95d9f.png)

In this block, you can assign a separate concentration file to whatever flow packages you like.  This is an alternative to the aux approach, which is still specified in the SOURCES block.

The SSMI6 file is a way to provide time-varying concentrations to the different flow packages.  At the moment, this file is list-based and uses the "settings" approach, which is why the concentration keyword is there.  An SSMI6 file looks like this:

![image](https://user-images.githubusercontent.com/3372403/129392589-819523fa-0655-40a2-9372-62a63170bc21.png)

This can evolve, but right now, the idea is that in the PERIOD block you provide the boundary number, the keyword CONCENTRATION, and then the concentration value (or a time series name).  This file will get huge for 2d arrays, like recharge, so we may need to support array-based input at some point, but I'm hopeful that time-varying point sources are the primary need.  (In looking back at your original post, you mention recharge, so you'll have to let me know how problematic  this list-based input is for arrays.)

**Comment by langevin-usgs** [comment]
@briochh, well it's been a long time to get this implemented, but I just merged in changes that should meet your use case.  There is a new input file for stress package concentrations (SPC) that can be assigned through the SSM Package to GWF stress packages.  This new SPC input file supports the READASARRAYS option for the case where READASARRAYS is used for RCH and EVT.  Time series and time-array series are implemented (if you need them), and there is new flexibility based on #773 that allows multiple GWT time steps and even stress periods when there is only one GWF stress period.  Let us know how it works if you get the chance to use it.

**Comment by briochh** [comment]
Sorry, @langevin-usgs. I had this on the back burner after plumbing in a workaround. Great work implimenting this feature. I'll get to testing it at my end ASAP.
