### ISSUE TITLE
Output times for ATS Utility

### ISSUE THREAD

**Issue by Smith0710** [MODFLOW-USGS/modflow6#764]
I have implemented the ATS for a stubborn model but alas it's still struggling. Apart from that, I am noticing that although  the OC6 period data are set to SAVE HEAD LAST, it seems the result is only saved when the last time step of the ATS scheme happens to be the same as the number of time steps in the in the TDIS period data, or else something else unexpected is happening. In my case only very few stress periods are being saved.

**Comment by Smith0710** [comment]
Looking again, it seems output is saved at the value of number of time steps in TDIS if that many or more time step are completed by the ATS scheme...

**Comment by langevin-usgs** [comment]
Thanks for pointing this out.  The ATS functionality is new, so it is good to hear about experiences with it.  Will take a look at this next week.  It would be helpful to see your TDIS, ATS, and OC input files to see if I can reproduce the problem.

**Comment by Smith0710** [comment]
Thanks @langevin-usgs for the follow-up . The current TDIS, ATS and OC file versions are attached. The first stress period is steady state and stress periods 2-199 are transient.
[CT7.zip](https://github.com/MODFLOW-USGS/modflow6/files/6942115/CT7.zip)

**Comment by langevin-usgs** [comment]
Hi @Smith0710, I think I fixed the issue that you were seeing.  The fix is on the development branch, and will be in our next official release.  Later this evening you will be able to download an executable with the fix from our nightly build repository located here (https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases).  

Thank you for reporting the issue!  We've tested ATS with our set of example problems, but it will be good to hear about additional experience.
