### ISSUE TITLE
Surface water control structures

### ISSUE THREAD

**Issue by MostafaGomaa93** [MODFLOW-USGS/modflow6#778]
Is there any plan in the next versions of MODFLOW 6 to include the capabilities of the Surface-water routing (SWR) Package?

For example:
1- the surface water control structures.
2- the 2D surface water flow with streams storage.

**Comment by rubencalje** [comment]
As I am exploring the possibilities of the SFR- and LAK-packages, I am also interested in this subject. Especially in scenario-analysis it can happen that a stream should stop draining because of backwater effects of a higher lake level downstream of the stream. This can also cause model instability, where more and more water enters the lake from the stream as groundwater levels around the lake rise, caused by the higher lake level.

Probably we are using the SFR- and LAK- packages in situations that they were not developed for. However, if there are plans to make the surface water calculation more advanced, either by including the SWR-package in Modflow 6, or building further on the SFR- and LAK- packages, we are interested.

**Comment by langevin-usgs** [comment]
SWR-like capabilities are included in our development plans.  Added to list of requested new model types.
