### ISSUE TITLE
Timeline for implementing GWT-GWT exchanges?

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#782]
Hello, will it eventually be possible to run exchanges between GWT models? If so, is there a time horizon for this?

**Comment by langevin-usgs** [comment]
Hi @RyanConway91, yes this is something that we are working on.  Our first step is supporting the GWF-GWF exchange in a more general manner so that we can allow XT3D to work across model domains.  That has been implemented and partially tested.  We will work next to extend this capability to GWT-GWT exchanges.  Might be looking at having some preliminary GWT-GWT capabilities in the next several months, with a more formal release early in 2022.

**Comment by langevin-usgs** [comment]
This has been implemented on develop and will be officially released in 6.3.0.
