### ISSUE TITLE
Very simple synthetic example for contaminant transport in a squared domain and constant flow velocities ?

### ISSUE THREAD

**Issue by BJEANNOT0** [MODFLOW-USGS/modflow6#914]
Hello,

I have a fairly simple simulation to run and I do not really know where to start in order to learn how to make it in modflow (I have never used the software before). Could you please give me an example or some indications on what to do ?

Here are the settings :
-I have a squared mesh of 81*81 pixels
-I know the flow velocity field, which is constant in time (I deal with 2D saturated flow).
-I know the initial concentrations of solute in water. There is no other input of solute afterwards.
-The solute is able to leave the domain by the sides of the domain (depending on the direction of the flow velocity field at the edges)

And i would like to model the evolution in time of the concentrations of solute in water.
Also, I do not want to use a graphical user interface (i.e. I would like to be able to run the simulation from a command line)

If possible, I would like to model both advection and diffusion processes (the  field of diffusion coefficient is  uniform).

Do you have a synthetic example  that resembles what I want to do ?
Thanks in advance for your help.
Best regards,

**Comment by mjr-deltares** [comment]
Hi,

I suggest you have a look at the MODFLOW 6 example set here:

https://modflow6-examples.readthedocs.io/en/master/

There's tons of material there and I think it contains all the ingredients you need, although it might be a bit spread out. In general, it would be advisable to set up your model with flopy:

https://flopy.readthedocs.io/en/3.3.4/introduction.html

and there too, you will find lots of examples and tutorials to get started. If you want to continue from there, have a look at the manual and the Input/Output guide for all supported functionality. These are included in the official MODFLOW release set.

Best regards

PS I will close this issue here, since it is not really concerned with code maintenance and improvement.
