### ISSUE TITLE
Stack overflow soon after reading input files

### ISSUE THREAD

**Issue by edesousa-intera** [MODFLOW-USGS/modflow6#923]
Running MF 6.3 ends in a stack overflow message (below), probably soon after reading input files (see list files). The same model runs in MF 6.2.2 without problem

![image](https://user-images.githubusercontent.com/85278435/158099065-eda65f4c-6326-47f0-b96a-9b4c0b52573e.png)
[mdo_v1.lst.txt](https://github.com/MODFLOW-USGS/modflow6/files/8241503/mdo_v1.lst.txt)
[mfsim.lst.txt](https://github.com/MODFLOW-USGS/modflow6/files/8241504/mfsim.lst.txt)

**Comment by langevin-usgs** [comment]
Thanks for reporting this.  We'd like to know what the problem is and we'll want to correct it as soon as possible.  Is it possible for you to provide the model itself to this issue so we can run it through the debugger?  We'd only need one stress period, since it happens so early in the simulation.  Alternatively, you could contact me through my work email and we can find another way to transfer the files.  Thanks.

**Comment by langevin-usgs** [comment]
Hey @edesousa-intera, did this get resolved?  Am closing for now, but feel free to reopen with information to reproduce this behavior.
