### ISSUE TITLE
GWF and GWT in same IMS solution does not behave well

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/modflow6#946]
Solving both flow (GWF) and transport (GWT) in the same IMS solution is unreliable.  In a few instances, a solution was obtained, but the mass balance for transport showed large discrepancies.  Should consider trapping for this with a warning or error condition in the MODFLOW 6 code.

This does not work well (in mfsim.nam)

```
BEGIN solutiongroup  1
  ims6  mysolver.ims  mygwfmodel mygwtmodel  
END solutiongroup  1
```

Instead do this

```
BEGIN solutiongroup  1
  ims6  mygwfsolver.ims  mygwfmodel
  ims6  mygwtsolver.ims  mygwtmodel  
END solutiongroup  1
```

**Comment by Huite** [comment]
I just wasted a day on this, happy to see it's already reported!

I've been getting `forrtl: error (72): floating overflow`, which are visible in the solution list file as well, with the maximum change bouncing up and then until it finally explodes (e.g. a value of 8.26004161+140).

I definitely think an error is definitely the way to go, rather than a warning. I've seen different behavior depending on:

* A drhodc value of 0.7142857142857143 versus 71428571428571 (last two decimals)
* Similarly, truncating some bottom decimals (0.9750000000000001 versus 0.975)
* Running a debug executable versus a release

Which makes it rather hard to debug, if you're not aware that your second option is the right way to do it...

Might also be worthwhile to add a statement to the io docs.

**Comment by langevin-usgs** [comment]
Yes, @Huite.  I agree that this needs an error message and statements in the IO doc.  Sorry for the wasted time.  Will get on it.
