### ISSUE TITLE
Model failed to converge with mf6.3

### ISSUE THREAD

**Issue by hjia1005** [MODFLOW-USGS/modflow6#948]
I have an mf6 model, I tried to use different mf6 versions to run it.

With mf6.0 it runs fast and converges nicely. However, when I run it using mf6.2 and 6.3, it stopped in the middle (sp=24, nper=50). I used exactly the same model files, what could be the reason? 

I am trying to update this model with the new ATS, TVK and TVS packages set up the PEST calibration, but convergency is a serious problem now.

Looking forward to any instructions. Thanks.

**Comment by langevin-usgs** [comment]
@hjia1005, there are many reasons why a model won't converge, and it's difficult for us to tell why your model doesn't converge with the latest version of MODFLOW because we don't know what packages and options you are using.  You will likely need to adjust the solver parameters and check for errors in your model.  If you find that there is an error in the MODFLOW program, then please report it here.
